### ISSUE TITLE
Parenthesis and asterisk trigger parsing errors

### ISSUE THREAD

**Issue by floo51** [yaniswang/HTMLHint#100] opened 2015-11-29 14:04 UTC
Angular 2 introduces a new syntax for attributes which can lead to this :

    <li *ng-for="#item of collection">
      <button (click)="action(item)">Do something</button>
    </li>

This is plain valid HTML but it triggers those 2 errors : 
 - Special characters must be escaped
 - Tag must be paired

**Comment by yaniswang** [comment] 2015-11-30 01:22
HTMLHint only support HTML code, your angular code is template, no supported.

**Comment by saeidzebardast** [comment] 2015-12-14 08:40
Same problem in Polymer when using $ in attribute name:
*  ([&lt;/div&gt;] Tag must pair)

```html
<div id$="[[myId]]">
  <content></content>
</div>
```

**Comment by floo51** [comment] 2016-02-05 19:04
Taken from the [W3C HTML specification](https://www.w3.org/TR/html-markup/syntax.html#syntax-attributes) : 

> Attribute names must consist of one or more characters other than the space characters, U+0000 NULL, """, "'", ">", "/", "=", the control characters, and any characters that are not defined by Unicode.

Following this rule, the code `<div my*attribute="" *ng-for="" id$=""></div>` is totally valid.

**Comment by szabyg** [comment] 2016-02-23 13:02
+1 We would need this as well. 
Any implementation hints, ideas, workaround?

**Comment by the-ult** [comment] 2016-02-24 20:18
+1

**Comment by david-gang** [comment] 2016-03-01 08:15
Hi @yaniswang ,

The issue is with the regular expression at: https://github.com/yaniswang/HTMLHint/blob/master/src/htmlparser.js#L36-L38

If we could make them unicode aware, we would solve the issue.

There are already projects working with regular expression and unicode like https://github.com/slevithan/xregexp

What do you think about this approach?

**Comment by mochtu** [comment] 2016-03-17 14:25
+1

**Comment by Zorgatone** [comment] 2016-04-18 13:22
+1:+1:

**Comment by felixfbecker** [comment] 2016-04-30 11:31
This is a serious bug... In a nutshell HTMLHint throwing errors on valid HTML. Can we please get a fix for this?

**Comment by Zorgatone** [comment] 2016-04-30 11:32
I totally agree @felixfbecker

**Comment by felixfbecker** [comment] 2016-04-30 11:38
Instead of whitelisting characters
```js
/\s*([\w\-:]+)(?:\s*=\s*(?:(")([^"]*)"|(')([^']*)'|([^\s"'>]*)))?/
```
it should use an inverted character class that includes anything but `"'>/=` and `NULL`:
```js
/\s*([^"'>/=\0]+)(?:\s*=\s*(?:(")([^"]*)"|(')([^']*)'|([^\s"'>]*)))?/
```

**Comment by felixfbecker** [comment] 2016-04-30 12:32
Made a PR

**Comment by yaniswang** [comment] 2016-05-01 02:49
Fixed now: https://github.com/yaniswang/HTMLHint/commit/b6a4d1a41994933bf183729c19ee61a32c872921

**Closed by yaniswang** 2016-05-01 02:49 UTC

**Comment by aaawhz** [comment] 2017-09-13 02:47
加上jsp语法吧， 我们很多页面都是用jsp写的。。。

**Comment by Zorgatone** [comment] 2017-09-13 08:34
So is this really parsing HTML using Regular Expressions?
![21414757_814231438744575_8699813647299847613_o](https://user-images.githubusercontent.com/2664036/30367644-0d1ae714-986f-11e7-81de-2a67c74ac2a5.png)
